### ISSUE TITLE
Make it possible to link a Direct Debit gateway account to a service

### ISSUE THREAD

**Issue by alexbishop1** [alphagov/pay-toolbox#177]
The link gateway accounts function currently only accepts gateway account IDs that are numeric, so it doesn’t work for Direct Debit gateway account IDs, which aren’t.

**Comment by sfount** [comment]
@alexbishop1 looks like it's trying to be too clever on the model https://github.com/alphagov/pay-toolbox/blob/master/src/web/modules/services/gatewayAccountRequest.model.ts#L9 -- will relax this
