### ISSUE TITLE
Add Google/ Apple Pay enabled information to Gateway Account

### ISSUE THREAD

**Issue by sfount** [alphagov/pay-toolbox#219]
Gateway accounts have a flag that allows users to pay with Apple/ Google Pay. 

It would be useful for engagement to know which accounts have this enabled. 

Show this data on the gateway account details page (`/gateway_accounts/:id`)

**Comment by nimalank7** [comment]
See [PR #225](https://github.com/alphagov/pay-toolbox/pull/225) which has been merged in.
