### ISSUE TITLE
Ability to view/edit user details

### ISSUE THREAD

**Issue by stephencdaly** [alphagov/pay-toolbox#25]
It would be useful to be able to see information about users, and edit certain fields.

In particular, it would be useful to be able to see/edit phone numbers as it is a common support request to change phone numbers used to send OTP codes for users.

**Comment by stephencdaly** [comment]
In addition to changing mobile numbers, being able to switch second factor method to sms would be useful if people lock themselves out of using the authenticator by not writing down the codes.

**Comment by sfount** [comment]
: +1 : to the switching second factor -- it would also be useful to re-generate the OTP key, this will prevent the previous authenticator from generating valid tokens.
