### ISSUE TITLE
Ability to see whether 3DS is enabled per service 

### ISSUE THREAD

**Issue by katiebates** [alphagov/pay-toolbox#44]

**Comment by mrlumbu** [comment]
definitely something that can be done with toolbox

**Comment by stephencdaly** [comment]
We already have this in the gateway account details, rather confusingly it's called "Toggle 3DS" though

![Screen Shot 2019-05-03 at 10 13 53](https://user-images.githubusercontent.com/5648592/57128737-414e2480-6d8c-11e9-9f40-c298adb2e618.png)

**Comment by nimalank7** [comment]
Can I submit a PR which renames 'Toggle 3DS' to '3DS Enabled'?

**Comment by stephencdaly** [comment]
Yes please "Toggle 3DS" is an awful name

**Comment by nimalank7** [comment]
See [PR #225](https://github.com/alphagov/pay-toolbox/pull/225) which has been merged in.
