### ISSUE TITLE
Ability to see which services use payment confirmation and refund emails 

### ISSUE THREAD

**Issue by katiebates** [alphagov/pay-toolbox#45]
And also whether collecting email address is set to optional

**Comment by sfount** [comment]
Closed by https://github.com/alphagov/pay-toolbox/pull/85

**Comment by stephencdaly** [comment]
![Screen Shot 2019-06-03 at 16 42 31](https://user-images.githubusercontent.com/5648592/58815489-972e1a80-861f-11e9-8ece-f5e7922625d9.png)
