### ISSUE TITLE
Ability to create Stripe account without bank details, responsible person, VAT number and company number

### ISSUE THREAD

**Issue by alexbishop1** [alphagov/pay-toolbox#48]
**As a** support person creating a new Stripe account with the toolbox
**I want** to be able to not specify the bank account number, sort code, responsible person name and address, VAT number and company number
**So that** the service user can provide these details themselves on the shiny new pages we have

This information shouldn’t be sent at all (although most of it can be overwritten, some of the pages will append rather than replace information and the company number can’t be changed at all once set).

The existing kitchen sink form will need to stick around for now while finish off the new pages.

**Comment by stephencdaly** [comment]
Note: VAT number (org_id) is currently required by toolbox. Requirement needs to be removed.

**Comment by sfount** [comment]
Fields that are required can be found in following `schema`.

Options: 
* Remove required fields to allow any or all data 
* Add new page that just allows name to be entered -- this will clear it up from a support user flow

**Comment by stephencdaly** [comment]
The new Stripe setup (currently on a branch) is not providing anything for `legal_entity.additional_owners`, so we get the following:
<img width="1105" alt="Screen Shot 2019-04-30 at 13 18 42" src="https://user-images.githubusercontent.com/5648592/56961062-9e5a9800-6b4a-11e9-9b77-05e64fe5d4dd.png">

We need to provide an empty list for `legal_entity.additional_owners` to avoid this.

**Comment by alexbishop1** [comment]
Ah, I ran into this too! I asked Stripe about it but they said not to worry about it because government agency accounts don’t need to provide ownership information.

**Comment by stephencdaly** [comment]
This was done as part of the firebreak work https://github.com/alphagov/pay-toolbox/pull/94
